Repository truenas/ports, pull requests merged in 2019-01, with the labels that each got.

#199 Revert "Update Netdata port"
  net-mgmt/netdata/Makefile
  net-mgmt/netdata/distinfo
  net-mgmt/netdata/files/patch-conf.d__health.d__ram.conf
  net-mgmt/netdata/files/patch-configure.ac
  net-mgmt/netdata/files/patch-src_common.c
  net-mgmt/netdata/files/patch-src_freebsd__sysctl.c
  net-mgmt/netdata/pkg-plist
Labels: review

#200 Suppress RAM Usage warnings
  net-mgmt/netdata/Makefile
  net-mgmt/netdata/files/patch-conf.d__health.d__ram.conf
Labels: review

#201 Update py-libzf port
  devel/py-libzfs/Makefile
  devel/py-libzfs/distinfo
Labels: review

#211 Samba backlog fix master
  net/samba49/Makefile
  net/samba49/files/0001-add-ix-custom-vfs-modules.patch
  net/samba49/files/0001-fix-listen-backlog.patch
Labels: backport-11.2

#214 tkt-71513: Update texinfo Port
  print/texinfo/Makefile
  print/texinfo/distinfo
Labels: Pending QA

#215 Update texinfo Port
  print/texinfo/Makefile
  print/texinfo/distinfo
Labels: review

#217 tkt-71849: Automatically enable zfsacl if sysvol supports nfs4 acls.
  net/samba49/files/0001-zfs-provisioning-patches.patch
Labels: backport-11.2

#219 tkt-72225: fix(net-mgmt/collectd5): Make rrdcached plugin report rrdc_update fai…
  net-mgmt/collectd5/files/patch-src__rrdcached.c
Labels: backport-11.3

#221 Update py-libzfs Port
  devel/py-libzfs/Makefile
  devel/py-libzfs/distinfo
Labels: review

#222 tkt-72984: Fix SSSD compatibilty with ldb14
  security/sssd/files/patch-src__monitor__monitor.c
Labels: backport-11.3
