Repository truenas/ports, pull requests merged in 2019-05, with the labels that each got.

#326 NAS-101325 / 11.3 / Update ws4py Port
  www/py-ws4py/Makefile
  www/py-ws4py/distinfo
  www/py-ws4py/files/patch-ws4py_client_____init____.py
  www/py-ws4py/files/patch-ws4py_streaming.py
  www/py-ws4py/files/patch-ws4py_utf8validator.py
Labels: skip jira status

#327 NAS-101325 / 12 / Update ws4py Port
  www/py-ws4py/Makefile
  www/py-ws4py/distinfo
  www/py-ws4py/files/patch-ws4py_client_____init____.py
  www/py-ws4py/files/patch-ws4py_streaming.py
  www/py-ws4py/files/patch-ws4py_utf8validator.py
Labels: review

#330 NAS-101747 / 11.3 / Explicitly map aceType to ae_entry_type in ixnas
  net/samba410/files/0001-add-ix-custom-vfs-modules.patch
Labels: backport-11.2

#331 Update py-libzfs port
  devel/py-libzfs/Makefile
  devel/py-libzfs/distinfo
Labels: review

#335 NAS-101788 / 11.2 / Don't send empty alerts
  sysutils/tw_cli/Makefile
  sysutils/tw_cli/files/407.status-3ware-raid.in
Labels: review

#328 NAS-101545 / 11.2 / Update Python 3.6.5 -> Python 3.6.8
  lang/python-doc-html/distinfo
  lang/python36/Makefile.version
  lang/python36/distinfo
  lang/python36/files/patch-Makefile.pre.in
  lang/python36/files/patch-Modules_grpmodule.c
  lang/python36/files/patch-Modules_pwdmodule.c
  lang/python36/files/patch-bpo35746
  lang/python36/files/patch-configure
  lang/python36/files/patch-configure.ac
  lang/python36/files/patch-issue20210
  lang/python36/files/patch-nss_reentrant_gil
  lang/python36/files/patch-pyconfig.h.in
  lang/python36/files/patch-setup.py
  lang/python36/pkg-plist
Labels: review

#336 NAS-101790 / 11.2 / Silence specific disk/udp alarms
  net-mgmt/netdata/Makefile
  net-mgmt/netdata/files/patch-conf.d_health.d_disks.conf
  net-mgmt/netdata/files/patch-conf.d_health.d_udp__errors.conf
Labels: backport-11.3, backported, review
