Repository truenas/ports, pull requests merged in 2019-04, with the labels that each got.

#288 Update py-libzfs port
  devel/py-libzfs/Makefile
  devel/py-libzfs/distinfo
Labels: review

#286 tkt-75928: Update rrdtool to 1.7.1
  databases/rrdtool/Makefile
  databases/rrdtool/distinfo
  databases/rrdtool/files/patch-src-rrd_xport.c
  databases/rrdtool/pkg-plist
Labels: backport-11.3

#258 tkt-77692: backport proftpd/proftpd@00e1d6c18cfd3f042ead5402c0847bd932d98e4e and…
  ftp/proftpd/Makefile
  ftp/proftpd/files/patch-contrib__mod_tls.c
  ftp/proftpd/files/patch-src__data.c
Labels: backport-11.1, backport-11.3

#292 Update py-libzfs port
  devel/py-libzfs/Makefile
  devel/py-libzfs/distinfo
Labels: review

#295 tkt-101233: Correct brand/logo for new boot loader in FN 12
  freenas/freenas-files/Makefile
  freenas/freenas-files/distinfo
  freenas/freenas-installer/Makefile
  freenas/freenas-installer/distinfo
  freenas/freenas-installer/pkg-plist
Labels: review

#301 NAS-100805 / 11.1 / sysutils/syslog-ng320
  sysutils/syslog-ng/Makefile
  sysutils/syslog-ng320/Makefile
  sysutils/syslog-ng320/distinfo
  sysutils/syslog-ng320/files/patch-configure
  sysutils/syslog-ng320/files/pkg-message.in
  sysutils/syslog-ng320/files/syslog-ng.conf.sample
  sysutils/syslog-ng320/files/syslog-ng.in
  sysutils/syslog-ng320/pkg-descr
  sysutils/syslog-ng320/pkg-plist
Labels: backport-11.2, backport-11.3, backported

#304 NAS-100805 / 11.3 / sysutils/syslog-ng320 (by themylogin) (by bugclerk)
  sysutils/syslog-ng/Makefile
  sysutils/syslog-ng320/Makefile
  sysutils/syslog-ng320/distinfo
  sysutils/syslog-ng320/files/patch-configure
  sysutils/syslog-ng320/files/pkg-message.in
  sysutils/syslog-ng320/files/syslog-ng.conf.sample
  sysutils/syslog-ng320/files/syslog-ng.in
  sysutils/syslog-ng320/pkg-descr
  sysutils/syslog-ng320/pkg-plist
Labels: skip jira status

#306 NAS-101377 / 11.2 / - Update to 2.7.15(include security fix)
  lang/python-doc-html/distinfo
  lang/python27/Makefile
  lang/python27/Makefile.version
  lang/python27/distinfo
  lang/python27/files/patch-issue30622
  lang/python27/pkg-plist
Labels: skip jira status

#305 NAS-100123 / 12 / Add 2FA dependencies
  freenas/py-middlewared/Makefile
Labels: skip jira status

#319 NAS-101511 / 11.3 / sysutils/dssystem: add default dssystem_enable
  sysutils/dssystem/Makefile
  sysutils/dssystem/files/dssystem.in
Labels: backport-11.1, backport-11.2, skip jira status

#320 NAS-101511 / 11.1 / sysutils/dssystem: add default dssystem_enable (by william-gr)
  sysutils/dssystem/Makefile
  sysutils/dssystem/files/dssystem.in
Labels: skip jira status
