Repository truenas/ports, pull requests merged in 2019-07, with the labels that each got.

#363 Update asigra
  sysutils/dsoperator/Makefile
  sysutils/dsoperator/distinfo
  sysutils/dssystem/Makefile
  sysutils/dssystem/distinfo
Labels: backport-11.3, backported

#381 NAS-102634 / 11.3 / properly set permissions on recycle repositories containing macros
  net/samba410/files/patch-source3__modules__vfs_recycle.c
Labels: backport-11.2

#385 NAS-100417 / 12 / Bug fix for libvirt port
  devel/libvirt/Makefile
Labels: skip jira status
