Repository truenas/ports, pull requests merged in 2020-04, with the labels that each got.

#624 NAS-105653 / 12.0 / Add support for JSON output to smbcacls and sharesec
  net/samba/Makefile
  net/samba/files/0001-samba_json.patch
Labels: jira

#641 NAS-105752 / 12.0 / Segfault fix for netifaces
  net/py-netifaces/Makefile
  net/py-netifaces/files/patch-netifaces.c
Labels: backport-11.3, jira

#621 NAS-105313 / 11.3 / Make collectd plugin report not only NFS client stat but also NFS ser…
  net-mgmt/collectd5/Makefile
  net-mgmt/collectd5/files/patch-src__nfsstat.c
Labels: backport-12
