Repository truenas/ports, pull requests merged in 2020-09, with the labels that each got.

#803 NAS-107465 / 20.10 / Ease netconf validation
  net/samba/Makefile
  net/samba/files/ease-netconf-validation.patch
Labels: backport-12.0, jira

#813 NAS-107146 / 20.10 / Bring sysutils/grub2 back and update it from git
  sysutils/grub2/Makefile
  sysutils/grub2/distinfo
  sysutils/grub2/pkg-descr
  sysutils/grub2/pkg-message
  sysutils/grub2/pkg-plist
Labels: backport-12.0

#815 NAS-107146 / 20.10 / sysutils/grub2-x86_64-efi
  sysutils/grub2-x86_64-efi/Makefile
  sysutils/grub2-x86_64-efi/distinfo
  sysutils/grub2-x86_64-efi/pkg-descr
  sysutils/grub2-x86_64-efi/pkg-message
  sysutils/grub2-x86_64-efi/pkg-plist
Labels: backport-12.0

#818 Update zettarepl port
  sysutils/py-zettarepl/Makefile
  sysutils/py-zettarepl/distinfo
Labels: backport-20.10

#821 NAS-107633 / 12.0 / Update security/gnutls to 3.6.15
  security/gnutls/Makefile
  security/gnutls/distinfo
  security/gnutls/pkg-plist
Labels: jira
