Repository truenas/ports, pull requests merged in 2020-07, with the labels that each got.

#721 Update zettarepl port
  sysutils/py-zettarepl/Makefile
  sysutils/py-zettarepl/distinfo
Labels: backport-12.0

#724 NAS-106694 / 12.1 / Samba:s3:modules:aio_fbsd - remove extra calloc()/free()
  net/samba/Makefile
  net/samba/files/experimental_aio.patch
  net/samba/files/tevent_kqueue.patch
Labels: backport-12.0, jira

#727 NAS-106702 / 12.1 / Samba:s3:smbd:dosmode - allow sparse flag to be set through vfs
  net/samba/Makefile
  net/samba/files/allow_vfs_set_sparse.patch
Labels: backport-12.0

#730 Update zettarepl port
  sysutils/py-zettarepl/Makefile
  sysutils/py-zettarepl/distinfo
Labels: backport-12.0

#732 NAS-106728 / 12.1 / Fixes for pkg in latest 12-stable
  ports-mgmt/pkg/Makefile
  ports-mgmt/pkg/distinfo
  ports-mgmt/pkg/pkg-plist
Labels: backport-12.0, jira

#735 NAS-106672 / 12.1 / Update py-libzfs port
  devel/py-libzfs/Makefile
  devel/py-libzfs/distinfo
Labels: backport-12.0

#734 NAS-106729 / 12.1 / Samba s3:smbd - add acl_brand to struct connection_struct
  net/samba/Makefile
  net/samba/files/0001-add-ix-custom-vfs-modules.patch
  net/samba/files/smbd-core-changes.patch
Labels: backport-12.0, jira

#737 NAS-106482 / 12.1 / update py-cam for nvme reservation support
  devel/py-cam/Makefile
  devel/py-cam/distinfo
Labels: backport-12.0

#741 NAS-106730 / 12.1 / Update Samba to 4.12.5
  net/samba/Makefile
  net/samba/distinfo
  net/samba/files/patch-lib__replace__system__passwd.h
  net/samba/pkg-plist
Labels: backport-12.0, jira

#743 fix py-cam build
  devel/py-cam/distinfo
Labels: backport-12.0

#748 NAS-106825 / 12.1 / Update zettarepl port
  sysutils/py-zettarepl/Makefile
  sysutils/py-zettarepl/distinfo
Labels: backport-12.0, jira

#751 NAS-106834 / 12.0 / Samba - s3:modules:smb_libzfs - fix caching bugs
  net/samba/Makefile
  net/samba/files/0001-add-ix-custom-vfs-modules.patch
  net/samba/files/add_zfs_based_vfs_modules.patch
Labels: jira

#753 NAS-106872 / 12.1 / Update py-libzfs port
  devel/py-libzfs/Makefile
  devel/py-libzfs/distinfo
Labels: backport-12.0, jira

#756 Bump OpenZFS for cache sizing bugfixes
  sysutils/openzfs-kmod/Makefile
  sysutils/openzfs-kmod/distinfo
  sysutils/openzfs/Makefile
  sysutils/openzfs/distinfo
Labels: backport-12.0, bug

#758 NAS-106962 / 12.1 / Update zettarepl port
  sysutils/py-zettarepl/Makefile
  sysutils/py-zettarepl/distinfo
Labels: backport-12.0, jira

#760 Fix rc.d/zfsd install
  sysutils/openzfs-kmod/Makefile
  sysutils/openzfs-kmod/distinfo
  sysutils/openzfs/Makefile
  sysutils/openzfs/distinfo
  sysutils/openzfs/pkg-plist
Labels: backport-12.0
