Repository truenas/ports, pull requests merged in 2020-10, with the labels that each got.

#827 NAS-107872 / 20.10 / stop stripping debug symbols at install for syslog-ng
  sysutils/syslog-ng325/Makefile
  sysutils/syslog-ng326/Makefile
Labels: backport-12.0

#829 NAS-105156 / 20.10 / net/rclone: Update to 1.52.2
  lang/go/Makefile
  lang/go/distinfo
  lang/go/files/patch-src_cmd_go_internal_modload_vendor.go
  net/rclone/Makefile
  net/rclone/distinfo
Labels: backport-12.0

#810 NAS-107510 / 12.0 / samba:lib:tevent_kqueue - fix looping in nmbd
  net/samba/Makefile
  net/samba/files/patch-source3__smbd__close.c
  net/samba/files/tevent_kqueue.patch
Labels: backport-20.10

#833 NAS-107960 / 20.10 / Add NSLCD_ACTION_STATE_GET to nslcd
  net/nss-pam-ldapd/Makefile
  net/nss-pam-ldapd/files/nslcd_action_state_get.patch
Labels: backport-12.0, jira

#841 NAS-107059 / 12.0 / Upgrade to intel-pcm-202009
  sysutils/intel-pcm/Makefile
  sysutils/intel-pcm/distinfo
  sysutils/intel-pcm/files/patch-Makefile
  sysutils/intel-pcm/files/patch-cpucounters.cpp
  sysutils/intel-pcm/files/patch-pci.cpp
  sysutils/intel-pcm/pkg-plist
Labels: backport-20.10

#844 NAS-106880 / 12.0 / Load registry service before trying to look up user shares
  net/samba/Makefile
  net/samba/files/registry_service.patch
Labels: backport-12.1

#835 NAS-107939 / 12.0 / textproc/libxml2: Multiple vulnerabilities
  textproc/libxml2/Makefile
  textproc/libxml2/distinfo
Labels: backport-20.10

#836 NAS-107938 / 12.0 / security/trousers: fix security issues
  security/trousers/Makefile
  security/trousers/files/patch-0a14b979.c
  security/trousers/files/patch-10b33821.c
  security/trousers/files/patch-c9b8c443.c
  security/trousers/files/patch-e74dd1d9.c
  security/trousers/files/patch-src_tcsd_svrside.c
Labels: backport-20.10

#837 NAS-107936 / 12.0 / Update to 7.72.0
  ftp/curl/Makefile
  ftp/curl/distinfo
  ftp/curl/pkg-plist
Labels: backport-20.10

#838 NAS-107937 / 12.0 / x11/toolcits-pango: Actually apply security patch
  x11-toolkits/pango/Makefile
  x11-toolkits/pango/files/patch-CVE-20191010238.c
Labels: backport-20.10

#811 NAS-107567 / 12.0 / s3:modules:smblibzfs fix empty snapshot detection
  net/samba/Makefile
  net/samba/files/0001-add-ix-custom-vfs-modules.patch
Labels: backport-12.1, jira

#850 NAS-108052 / 12.0 / Update to samba 4.12.8
  net/samba/Makefile
  net/samba/distinfo
  net/samba/files/patch-source3__smbd__close.c
Labels: jira

#853 NAS-108063 / 20.12 / BUILD_DEPENDS=git:devel/git for grub2
  sysutils/grub2-x86_64-efi/Makefile
  sysutils/grub2/Makefile
Labels: backport-12.0

#856 NAS-108023 / 20.12 / Update google-api-python-client
  devel/py-protobuf/Makefile
  devel/py-protobuf/distinfo
  security/py-google-auth/Makefile
  security/py-google-auth/distinfo
  security/py-google-auth/pkg-descr
  www/py-google-api-core/Makefile
  www/py-google-api-core/distinfo
  www/py-google-api-core/pkg-descr
  www/py-google-api-python-client/Makefile
  www/py-google-api-python-client/distinfo
Labels: backport-12.0

#858 NAS-108073 / 12.0 / Make sysutils/grub2 not expired
  sysutils/grub2-x86_64-efi/Makefile
  sysutils/grub2/Makefile
Labels: backport-20.12

#859 NAS-108063 / 20.12 / Fix building grub
  sysutils/grub2-x86_64-efi/Makefile
  sysutils/grub2/Makefile
Labels: backport-12.0

#862 NAS-108063 / 20.12 / Fix building grub
  sysutils/grub2-x86_64-efi/Makefile
  sysutils/grub2/Makefile
Labels: backport-12.0

#864 NAS-108063 / 20.12 / Fix building grub
  sysutils/grub2-x86_64-efi/Makefile
  sysutils/grub2/Makefile
Labels: backport-12.0

#866 NAS-108063 / 20.12 / Fix building grub
  sysutils/grub2/pkg-plist
Labels: backport-12.0
