Repository truenas/ports, pull requests merged in 2020-02, with the labels that each got.

#549 NAS-104976 / 12.0 / Add parameter to store DOS attributes in xattrs to ixnas
  net/samba/Makefile
  net/samba/files/0001-add-ix-custom-vfs-modules.patch
Labels: jira

#551 NAS-105028 / 12.0 / Add smbtorture test for ixnas
  net/samba/Makefile
  net/samba/files/ix-smbtorture.patch
Labels: backport-11.3

#565 NAS-105034 / 11.3 / Do not allow minio to create bogus pool directories in /mnt tmpfs
  www/minio/Makefile
  www/minio/files/minio.in
Labels: backport-12

#559 NAS-105071 / 11.3 / Issues/optimize shadow copy zfs
  net/samba410/Makefile
  net/samba410/files/0001-add-ix-custom-vfs-modules.patch
  net/samba410/files/add_zfs_based_vfs_modules.patch
Labels: backport-12, jira

#561 NAS-105130 / 11.3 / Use openat() in Samba debug logs
  net/samba410/Makefile
  net/samba410/files/debug.patch
Labels: jira

#570 NAS-105214 / 12.0 / Optimize shadow copies
  net/samba/Makefile
  net/samba/files/0001-add-ix-custom-vfs-modules.patch
  net/samba/files/0001-add-shadow_copy_zfs.patch
  net/samba/files/add_zfs_based_vfs_modules.patch
  net/samba/files/smbd-core-changes.patch
  net/samba/files/source3__smbd__reply.c.patch
Labels: jira
