Repository truenas/ports, pull requests merged in 2020-08, with the labels that each got.

#764 NAS-107027 / 12.1 / Add JRA async DNS patches to samba
  net/samba/Makefile
  net/samba/files/dns-fixes.patch
Labels: jira

#781 NAS-107060 / 12.0 / Report read/write bytes for NFS server
  net-mgmt/collectd5/Makefile
  net-mgmt/collectd5/files/patch-src__nfsstat.c
Labels: backport-12.1

#793 NAS-107055 / 12.0 / Fix excessive log entries from vfs_fruit
  net/samba/Makefile
  net/samba/files/patch-source3__modules__vfs_fruit.c
Labels: backport-12.1

#797 NAS-107391 / 11.3 / samba - s3: fix handling of large xattrs
  net/samba410/Makefile
  net/samba410/files/0001-add-support-for-xattrs-larger-than-64k.patch
Labels: backport-12.0, backport-12.1, jira
