Repository truenas/ports, pull requests merged in 2020-06, with the labels that each got.

#681 NAS-106339 / 12.0 / Samba:lib:tevent - add support for AIO kevents
  net/samba/Makefile
  net/samba/files/experimental_aio.patch
  net/samba/files/tevent_kqueue.patch
Labels: jira

#672 NAS-106047 / 11.3 / Samba s3:modules:vfs_ixnas - fix automatic dataset creation option
  net/samba410/Makefile
  net/samba410/files/0001-add-ix-custom-vfs-modules.patch
Labels: backport-12.0, jira

#690 NAS-106450 / 12.0 / Samba:lib:tevent add handling for timed, signal, and immediate events
  net/samba/Makefile
  net/samba/files/tevent_kqueue.patch
Labels: jira

#702 NAS-106500 / 11.3 / Samba: update to 4.10.16
  net/samba410/Makefile
  net/samba410/distinfo
  net/samba410/files/patch-lib__replace__system__passwd.h
  net/samba410/pkg-plist
Labels: jira

#704 NAS-106390 / 11.3 / Samba:nsswitch:pam_winbind - make openpam happy with error codes
  net/samba410/Makefile
  net/samba410/files/pam_winbind_openpam.patch
Labels: backport-12.0

#705 NAS-106390 / 12.0 / Samba:nsswitch:pam_winbind - make openpam happy with error codes (by anodos325)
  net/samba/Makefile
  net/samba/files/silence-openpam-warnings.patch
Labels: backport-12.0

#680 NAS-106288 / 12.1 / Update py-kmip port
  devel/py-kmip/Makefile
  devel/py-kmip/distinfo
Labels: backport-12.0, skip jira status

#710 Update zettarepl port
  sysutils/py-zettarepl/Makefile
  sysutils/py-zettarepl/distinfo
Labels: backport-12.0

#714 NAS-106629 / 12.1 / Samba:s3:winbindd:idmap_ad fix null pointer dereference
  net/samba/Makefile
  net/samba/files/fix-idmap_ad.patch
Labels: backport-11.3, backport-12.0, jira

#718 Samba:s3:modules:vfs_ixnas - apply robocopy workaround / optimization
  net/samba/Makefile
  net/samba/files/0001-add-ix-custom-vfs-modules.patch
Labels: backport-12.0
