Repository truenas/ports, pull requests merged in 2020-12, with the labels that each got.

#909 NAS-108491 / 12.0 / lib/tevent - fix processing of messaging idle timer
  net/samba/Makefile
  net/samba/files/tevent_kqueue.patch
Labels: backport-12.1, jira

#911 NAS-108528 / 12.0 / samba: improve aio scalability
  net/samba/Makefile
  net/samba/files/experimental_aio.patch
  net/samba/files/tevent_kqueue.patch
Labels: backport-12.1, jira

#912 NAS-108501 / 12.0 / samba - fix shadow copy browsing
  net/samba/Makefile
  net/samba/files/0001-add-ix-custom-vfs-modules.patch
  net/samba/files/add_zfs_based_vfs_modules.patch
  net/samba/files/ix-smbtorture.patch
  net/samba/files/patch-source3__modules__vfs_fruit.c
  net/samba/files/smbd-core-changes.patch
Labels: WIP

#914 NAS-108561 / 12.0 / s3:smbd:trans2 - fix smbd_do_qfsinfo for vss_tval
  net/samba/Makefile
  net/samba/files/smbd-core-changes.patch
Labels: backport-12.1, jira

#917 NAS-108596 / 12.0 / lib:tevent - switch back to default (non-kqueue) timers
  net/samba/Makefile
  net/samba/files/experimental_aio.patch
  net/samba/files/tevent_kqueue.patch
Labels: jira

#918 NAS-108605 / 12.0 / s3:smbd:trans2.c - fix NULL deref over SMB1 protocol
  net/samba/Makefile
  net/samba/files/smbd-core-changes.patch
Labels: jira

#916 NAS-108587 / 12.0 / s3:smbd - fix smb2_query_directory for shadow copies
  net/samba/Makefile
  net/samba/files/add_zfs_based_vfs_modules.patch
  net/samba/files/smbd-core-changes.patch
  net/samba/files/tevent_kqueue.patch
Labels: jira

#925 NAS-108726 / 12.0 / sysutils/htop: Update to 3.0.2
  sysutils/htop/Makefile
  sysutils/htop/distinfo
  sysutils/htop/files/patch-freebsd_FreeBSDProcessList.c
  sysutils/htop/pkg-descr
Labels: backport-21.02

#927 NAS-108836 / 12.0 / net/netatalk3 - fix off-by-one error in conversion of EA list
  net/netatalk3/Makefile
  net/netatalk3/files/patch-libatalk__vfs__extattr.c
Labels: jira
