Repository truenas/ports, pull requests merged in 2020-11, with the labels that each got.

#872 NAS-106424 / 20.12 / fix building xe-guest-utilities and xen-guest-tools ports
  sysutils/xe-guest-utilities/Makefile
  sysutils/xe-guest-utilities/files/xenguest.in
  sysutils/xen-guest-tools/Makefile
  sysutils/xen-guest-tools/distinfo
  sysutils/xen-guest-tools/files/patch-fsys_zfs.h
  sysutils/xen-guest-tools/files/patch-tools-Makefile
Labels: backport-12.0

#874 NAS-108172 / 12.0 / s3:modules:ixnas - add ntimes workaround
  net/samba/Makefile
  net/samba/files/0001-add-ix-custom-vfs-modules.patch
Labels: backport-20.12, jira

#876 NAS-107753 / 12.0 / Update openldap to 2.4.51 and increment portrevision of related ports
  net/nss-pam-ldapd/Makefile
  net/openldap24-server/Makefile
  net/openldap24-server/distinfo
  net/openldap24-server/files/patch-libraries_liblmdb_mdb.c
  net/openldap24-server/pkg-descr
  net/openldap24-server/pkg-descr.client
  net/openldap24-server/pkg-plist.client
  net/py-ldap/Makefile
  net/samba/Makefile
Labels: backport-12.1

#877 NAS-107957 / 12.0 / s4:libnet:py-net - fix resource leak
  net/samba/Makefile
  net/samba/files/patch-source4__libnet__py_net.c
Labels: backport-12.1

#889 NAS-107830 / 12.0 / sysutils/py-psutil: support retrieving process jail ID
  sysutils/py-psutil/Makefile
  sysutils/py-psutil/files/patch--psutil--__init__.py
  sysutils/py-psutil/files/patch--psutil--_psbsd.py
  sysutils/py-psutil/files/patch--psutil--_psutil_bsd.c
Labels: backport-20.12

#895 NAS-108356 / 20.12 / Update py-libzfs port
  devel/py-libzfs/Makefile
  devel/py-libzfs/distinfo
Labels: backport-12.0, backported, jira

#901 NAS-108442 / 12.0 / lib:tevent:tevent_kqueue - fix leak of tevent_timer struct
  net/samba/Makefile
  net/samba/files/tevent_kqueue.patch
Labels: backport-12.1, jira
