Repository truenas/ports, pull requests merged in 2020-01, with the labels that each got.

#490 NAS-104578 / 11.3 / Update security/py-paramiko
  security/py-paramiko/Makefile
  security/py-paramiko/distinfo
Labels: jira

#517 NAS-104694 / 11.3 / Ensure rcs57 is installed as a dependency for iocage
  sysutils/iocage/Makefile
Labels: backport-12, backported

#521 NAS-104710 / 11.2 / Update vfs_noacl to latest version from 11.3-stable
  net/samba49/files/0001-add-ix-custom-vfs-modules.patch
Labels: jira

#520 NAS-104703 / 11.3 / Only show relevant previous versions of files and directories.
  net/samba410/Makefile
  net/samba410/files/add_zfs_based_vfs_modules.patch
Labels: jira

#528 NAS-104757 / 12.0 / Update py-libzfs port
  devel/py-libzfs/Makefile
  devel/py-libzfs/distinfo
Labels: backport-11.3, backported
