Repository truenas/ports, pull requests merged in 2021-02, with the labels that each got.

#948 NAS-108940 / 12.0 / Fix NFS read stats reporting write stats
  net-mgmt/collectd5/files/patch-src__nfsstat.c
Labels: backport-21.02

#953 NAS-109254 / 12.0 / Collect demand_metadata_misses
  net-mgmt/collectd5/Makefile
  net-mgmt/collectd5/files/patch-src_zfs__arc.c
Labels: backport-21.02

#942 NAS-109352 / 12.0 / net/samba - update to 4.12.11
  net/samba/Makefile
  net/samba/distinfo
  net/samba/files/patch-source3__smbd__close.c
Labels: jira

#943 NAS-109158 / 12.0 / s3:modules:ixnas - fix ntacl handling for linux clients with cifsacl
  net/samba/Makefile
  net/samba/files/0001-add-ix-custom-vfs-modules.patch
Labels: jira

#966 NAS-109014 / 12.0 / sysutils/smartmontools: update to 7.2
  sysutils/smartmontools/Makefile
  sysutils/smartmontools/distinfo
  sysutils/smartmontools/files/smart.in
Labels: backport-21.04
