Repository truenas/ports, pull requests merged in 2022-03, with the labels that each got.

#1172 NAS-115352 / 13.0 / Backport paramiko/paramiko@3853951b304c34a97ddb39204c5b47d944f2498a
  security/py-paramiko/Makefile
  security/py-paramiko/files/patch-paramiko__util.py
Labels: skip jira status

#1175 NAS-115532 / 13.0 / net/netatalk3 - fix multiple CVEs
  net/netatalk3/Makefile
  net/netatalk3/files/CVE_FIXES.patch
Labels: jira, backport-12.0

#1178 NAS-115575 / 13.0 / fix graphics/drm-fbsd13-kmod
  graphics/drm-current-kmod/Makefile
  graphics/drm-current-kmod/distinfo
  graphics/drm-devel-kmod/Makefile
  graphics/drm-devel-kmod/distinfo
  graphics/drm-fbsd13-kmod/Makefile
  graphics/drm-fbsd13-kmod/distinfo
Labels: jira
